### PR TITLE
build: Update Gradle wrapper to 6.9.1

### PR DESCRIPTION
**Pull request by EwoutH**
Update the Gradle wrapper from 6.6 to [6.9.1](https://github.com/gradle/gradle/releases/tag/v6.9.1) (the latest 6.x release).

### CODE REVIEW

**Comment by EwoutH** [comment]
@Spasi I'm doing some cleanup of old, open PRs. If you would like to get these changes in, please leave a reply or review.

In two weeks I will close this PR if no reaction received.

**Comment by SWinxy** [comment]
looks like the latest is 6.9.3. do we use any [deprecated things](https://docs.gradle.org/6.9.3/userguide/upgrading_version_6.html#changes_6.9) that would be a problem in 7.x? ugh.

**Comment by EwoutH** [comment]
I think the (recommended) way is to update to 6.9.x first, look for (and fix) deprecation warnings, and then upgrade to 7.x.

**Comment by JT122406** [comment]
This Pr should be closed in favor of #844

**Comment by Spasi** [comment]
Thank you @EwoutH and sorry for the long delay! Gradle is only used for deploying snapshots and it's a low priority to move to newer versions.

#844 has been merged instead of this PR.

**Pull request closed without merging**
