### PR TITLE
First HWLOC Additions

### PR DESCRIPTION
**Pull request by Sylvyrfysh**
Brings HWLOC branch up to 3.1.5 and adds beginning types

### CODE REVIEW

**Comment by Sylvyrfysh** [comment]
This should be good for the base commit. I'll keep working on adding when I have the time

**Comment by Spasi** [comment]
Hey @Sylvyrfysh,

Do you think you'll be able to continue work on this PR? Other than fixing the current conflicts, the template DSL will also have to be updated to the latest version.

Btw, LWJGL now includes a tool that extracts template definitions from C/C++ headers, including documentation. I would recommend using it to recreate all templates and then adding the necessary modifiers (`AutoSize` etc).

**Comment by Sylvyrfysh** [comment]
Yeah, I'll get back to this and restart what's needed.

**Comment by Sylvyrfysh** [comment]
hwloc 2.0 or old stable 1.11? 2.0 is extremely new, and supports modern processor layouts. 1.11 is the ultrastable branch but may not work as well on newer systems

**Comment by Spasi** [comment]
The latest release (2.0.2) looks stable enough now, I don't see a reason to go with 1.11.

**Pull request closed without merging**
