### PR TITLE
Add support for Linux RISC-V 64 

### PR DESCRIPTION
**Pull request by Glavo**
Most of the work has been completed, and both cross compilation and native compilation can work. I have successfully launched Minecraft on Debian RISC-V 64.

image

Currently, the dependent native libraries are all built by me on my own machine. Next, I need to have LWJGL CI build the native libraries for RISC-V.

Progress:

- [x] [assimp](https://github.com/LWJGL-CI/assimp)
- [x] [bgfx](https://github.com/LWJGL-CI/bgfx)
- [x] [FreeType](https://github.com/LWJGL-CI/freetype)
- [x] [GLFW](https://github.com/LWJGL-CI/glfw)
- [x] [HarfBuzz](https://github.com/LWJGL-CI/harfbuzz)
- [x] [hwloc](https://github.com/LWJGL-CI/hwloc)
- [x] [jemalloc](https://github.com/LWJGL-CI/jemalloc)
- [x] [KTX Software](https://github.com/LWJGL-CI/KTX-Software)
- [x] [OpenAL Soft](https://github.com/LWJGL-CI/openal-soft)
- [x] [OpenXR SDK](https://github.com/LWJGL-CI/OpenXR-SDK)
- [x] [Opus](https://github.com/LWJGL-CI/opus)
- [x] [Shaderc](https://github.com/LWJGL-CI/shaderc)
- [x] [SPIRV-Cross](https://github.com/LWJGL-CI/SPIRV-Cross)

### CODE REVIEW

**Comment by Glavo** [comment]
@Spasi 

I'm running into a little trouble.

I disabled the bgfx module for RISC-V 64. However, the nanovg module contains a class ([NanoVGBGFX](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/nanovg/src/generated/java/org/lwjgl/nanovg/NanoVGBGFX.java)) that depends on bgfx. When the bgfx module is disabled, the class cannot be compiled either (because several invokeXXX methods are missing in `org.lwjgl.system.JNI`).

I guess this is a known thing since I saw in the template that the class is only generated when the bgfx module is enabled ([nanovg_bgfx.kt](https://github.com/LWJGL/lwjgl3/blob/00db5ae179cf1b7d96614fe087a314e29e203acb/modules/lwjgl/nanovg/src/templates/kotlin/nanovg/templates/nanovg_bgfx.kt#LL11C32-L11C41)). But unfortunately, unless I run `ant clean` first and then turn on offline mode before building, the class always appears.

I know that the generator of LWJGL caches generated classes, so I'm guessing the cause of the problem is that the generator doesn't delete classes that shouldn't be there. But I'm not familiar with the generator, so can you take a look at this problem?

**Comment by Spasi** [comment]
@Glavo That's correct, the generator is not clever enough to delete previously generated code that is no longer needed. Also, `ant clean` will only clean directories of currently enabled modules.

I've verified that with a fully clean/reset repo and bgfx disabled in `config/build-bindings.xml`, the `NanoVGBGFX` class is not generated and LWJGL builds correctly. Just make sure to not use `ant hydrate-kotlinc`, that will generate everything again. Use `ant compile-templates` instead (slow, but necessary in this case).

**Comment by Glavo** [comment]
> @Glavo That's correct, the generator is not clever enough to delete previously generated code that is no longer needed. Also, `ant clean` will only clean directories of currently enabled modules.
> 
> I've verified that with a fully clean/reset repo and bgfx disabled in `config/build-bindings.xml`, the `NanoVGBGFX` class is not generated and LWJGL builds correctly. Just make sure to not use `ant hydrate-kotlinc`, that will generate everything again. Use `ant compile-templates` instead (slow, but necessary in this case).

I understand. Thank you.

**Comment by Slackadays** [comment]
I just spent a few hours working on the same thing, so hopefully I can help progress this PR!

**Comment by Slackadays** [comment]
There is an issue with compiling this on a VisionFive 2 running the Debian image with OpenJDK 19:

```
javac: nanovg] /home/user/lwjgl3-riscv/lwjgl3-riscv-existing/modules/lwjgl/nanovg/src/generated/java/org/lwjgl/nanovg/NanoVGBGFX.java:72: error: cannot find symbol
[javac: nanovg]         return invokeCPP(_edgeaa, _viewId, _allocator, __functionAddress);
[javac: nanovg]                ^
[javac: nanovg]   symbol:   method invokeCPP(int,short,long,long)
[javac: nanovg]   location: class NanoVGBGFX
[javac: nanovg] /home/user/lwjgl3-riscv/lwjgl3-riscv-existing/modules/lwjgl/nanovg/src/generated/java/org/lwjgl/nanovg/NanoVGBGFX.java:97: error: cannot find symbol
[javac: nanovg]         invokePCV(_ctx, _viewId, __functionAddress);
[javac: nanovg]         ^
[javac: nanovg]   symbol:   method invokePCV(long,short,long)
[javac: nanovg]   location: class NanoVGBGFX
[javac: nanovg] /home/user/lwjgl3-riscv/lwjgl3-riscv-existing/modules/lwjgl/nanovg/src/generated/java/org/lwjgl/nanovg/NanoVGBGFX.java:158: error: cannot find symbol
[javac: nanovg]         invokeCPV(_view_id, _framebuffer, __functionAddress);
[javac: nanovg]         ^
[javac: nanovg]   symbol:   method invokeCPV(short,long,long)
[javac: nanovg]   location: class NanoVGBGFX
[javac: nanovg] /home/user/lwjgl3-riscv/lwjgl3-riscv-existing/modules/lwjgl/nanovg/src/generated/java/org/lwjgl/nanovg/NanoVGBGFX.java:172: error: cannot find symbol
[javac: nanovg]         invokePCV(_ctx, _id, _width, _height, flags, __functionAddress);
[javac: nanovg]         ^
[javac: nanovg]   symbol:   method invokePCV(long,short,int,int,int,long)
[javac: nanovg]   location: class NanoVGBGFX
[javac: nanovg] 4 errors
[javac: nanovg] 1 warning
```

Looking in my own lwjgl3 fork, it appears that this symbol does exist as just a function declaration. What differences would cause your version to not make this symbol?

**Comment by Glavo** [comment]
@Slackadays Hey, the problem you encountered was mentioned in the previous conversation. Here is Spasi's reply to this:

> That's correct, the generator is not clever enough to delete previously generated code that is no longer needed. Also, `ant clean` will only clean directories of currently enabled modules.
> 
> I've verified that with a fully clean/reset repo and bgfx disabled in `config/build-bindings.xml`, the `NanoVGBGFX` class is not generated and LWJGL builds correctly. Just make sure to not use `ant hydrate-kotlinc`, that will generate everything again. Use `ant compile-templates` instead (slow, but necessary in this case).

**Comment by Slackadays** [comment]
One more thing: I'm trying to get the tests working, and it looks like `rpmalloc` was removed specifically for RISC-V in https://github.com/LWJGL/lwjgl3/pull/890/commits/f2062730c7020e678df266109eaf024626061ee8. However, it seems to compile just fine, so is there a specific reason it was disabled?

**Comment by Glavo** [comment]
> One more thing: I'm trying to get the tests working, and it looks like `rpmalloc` was removed specifically for RISC-V in [f206273](https://github.com/LWJGL/lwjgl3/commit/f2062730c7020e678df266109eaf024626061ee8). However, it seems to compile just fine, so is there a specific reason it was disabled?

Sorry, I forgot why I did this. I will re-review these temporarily disabled modules when the issues blocking this PR are resolved.

**Comment by Slackadays** [comment]
It turns out that there was an issue with rpmalloc which prevented it from properly working on RISC-V, but https://github.com/Glavo/lwjgl3/pull/1 should fix that. Unfortunately, the tests hang at OpenCL probably because the VF2's Imagination drivers are pure junk right now, so that might improve sometime in the future.

**Comment by Glavo** [comment]
@Spasi There has been no progress on this PR for several months. Can you please take a look at these PRs?

https://github.com/LWJGL-CI/opus/pull/5
https://github.com/LWJGL-CI/shaderc/pull/2
https://github.com/LWJGL-CI/OpenXR-SDK/pull/1
https://github.com/LWJGL-CI/hwloc/pull/1
https://github.com/LWJGL-CI/KTX-Software/pull/1
https://github.com/LWJGL-CI/assimp/pull/8

**Comment by Glavo** [comment]
long wait……

**Comment by Slackadays** [comment]
@Spasi these PRs let RISC-V become viable for Minecraft and anything else that uses LWJGL

**Comment by Glavo** [comment]
I'll run some tests right away to see if there are any issues that need to be addressed.

**Comment by Glavo** [comment]
@Spasi I have successfully built LWJGL on RISC-V platform and it passes all tests. This PR is now pending review.

image

**Comment by Glavo** [comment]
GitHub Action is working: https://github.com/Glavo/lwjgl3/actions/runs/6803359632

image

**Comment by Spasi** [comment]
Thank you @Glavo and @Slackadays! The first 3.3.4 snapshot will include riscv64 binaries.

**Comment by SimonIT** [comment]
When do you think the snapshot will be available?

**Comment by Spasi** [comment]
@SimonIT it's up, I published it before going to bed and updated https://www.lwjgl.org/customize about an hour ago.

**Pull request merged**
