### PR TITLE
bgfx module

### PR DESCRIPTION
**Pull request by code-disaster**
Following up to http://forum.lwjgl.org/index.php?topic=6315.0, here's a PR to open my doings for your feedback.

I also moved all examples which require assets over to lwjgl3-demos.

### CODE REVIEW

**Comment by Spasi** [comment]
The bgfx bindings are now complete, including documentation. There have been changes to several functions and structs, mostly because of missing `AutoSize` modifiers.

**Comment by kappaOne** [comment]
Nice work. There have been substantial changes (module system) and additions (BGFX) to LWJGL since the 3.0.0 release, a lot more than one would expect for a point release, maybe bump the next release version to 3.1 instead of 3.0.1?

**Comment by Spasi** [comment]
> maybe bump the next release version to 3.1 instead of 3.0.1?

Makes sense, yes.

**Comment by dustContributor** [comment]
I noticed only recently there were bgdx bindings, great work dude! :smile:

**Pull request merged**
