### PR TITLE
changed library names to constants

### PR DESCRIPTION
**Pull request by Noviv**
I love LWJGL and I would like to help out in any way possible (I'm pretty young and still learning this whole programming thing)! I thought this might be better because there were multiple strings with the same value across this file.

### CODE REVIEW

**Comment by Spasi** [comment]
Duplicate string literals are only stored **once** in the class file and at runtime. So, this change doesn't do anything useful, though it doesn't hurt either.

Since you're a young programmer I'm going to merge this pull request, if only to encourage you in contributing more to open source software. But... only if you complete the following tasks:

- Rename the variables to `LWJGL_LIBRARY_PATH` and `JAVA_LIBRARY_PATH`.
- Apply the [The seven rules of a great git commit message](http://chris.beams.io/posts/git-commit/), i.e. the commit should read "Change library names to constants" or "Extract library names to constants".
- Update this pull request **without** creating a new commit.

:)

**Comment by Noviv** [comment]
Thank you so so very much! I will get right on it during my lunch period!

Quick question: how do I change the commit that I made to this PR without pushing another commit? Do I have to revert that commit and push a new one to my fork?

P.S. I promise my next PRs will be more useful!

**Comment by kenzierocks** [comment]
http://rebaseandsqua.sh

On Thursday, September 24, 2015, Matthew Webb <notifications@github.com>
wrote:

> Thank you so so very much! I will get right on it during my lunch period!
>
> Quick question: how do I change the commit that I made to this PR without
> pushing another commit? Do I have to revert that commit and push a new one
> to my fork?
>
> P.S. I promise my next PRs will be more useful!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LWJGL/lwjgl3/pull/89#issuecomment-142988240>.
>


-- 
~Kenzie Togami

**Comment by Noviv** [comment]
Alright, @Spasi , I fixed it! Also, thank you @kenzierocks , I now know how to rebase a commit haha

**Comment by Spasi** [comment]
Thank you!

**Comment by Noviv** [comment]
Hey @Spasi , I'm sorry to bother you on a closed PR, but I am having some trouble: I am trying to import the entire LWJGL3 source into an IDE, and so far I have had no success. How do I set up LWJGL in an IDE (Netbeans, Eclipse, BlueJ, IntelliJ, I don't care) such that I can edit code in the modules?

**Comment by Spasi** [comment]
Hey @Noviv, the repository contains a pre-configured IntelliJ project in the [config/ide/idea](https://github.com/LWJGL/lwjgl3/tree/master/config/ide/idea) directory. No one has contributed a project for other IDEs so far.

**Comment by httpdigest** [comment]
@Spasi, @Noviv: If you don't mind then I'll PR my Eclipse project configuration (.project and .classpath) inside the config/ide/eclipse folder. Those are created in Eclipse Luna (4.4), but should work with any previous Eclipse versions.

**Comment by Noviv** [comment]
Thank you @httpdigest and @Spasi , I will stop bothering you now! :D

**Comment by httpdigest** [comment]
Okay, pull is in: https://github.com/LWJGL/lwjgl3/pull/90

**Pull request merged**
